Решение первой задачи
js-tasks-ru/jsbasic-20200903_alexey-nechaev1988 pull request #1
Opened 2020-09-07 09:49 UTC by NoldorN

2020-09-07 09:57 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-08 14:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Проверка на спам
- должна возвращать true для 'free xxxxx'
- должна возвращать false для 'innocent rabbit'
- должна возвращать true для '1XbeT now'
```
```diff
Допишите функцию валидации имени пользователя
- если меньше 4 символов то false
- если содержит пробелы, то false
- если имя корректное, то true
```
```diff
Сделать первый символ заглавным
- должна делать первый символ заглавным
- должна работать для пустой строки
- должна работать для строки из одной буквы
```
```diff
Первая задача
+ 1+1=2
```
```diff
Вычислить факториал
- факториал 1 равен 1
- факториал 0 равен 1
- факториал 5 равен 120 
- факториал 3 равен 6 
```
```diff
Усечение строки
- должна не трогать короткую строку 
- должна усекать строку 
```

2020-09-08 15:51 UTC, koalex requested changes
тесты на проходят. Попробуй у себя выполнить `npm test`

2020-09-09 04:13 UTC, koalex requested changes
Теперь у тебя конфликт. Если не знаешь как исправить, то напиши мне в личку.

2020-09-09 10:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-09-10 07:01 UTC, koalex approved these changes
всё ОК

2020-09-10 07:01 UTC, merged